# Generated by Django 5.0.4 on 2024-05-22 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='Name of vacancy')),
                ('city', models.CharField(max_length=30, null=True, verbose_name='The city of job')),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('description', models.TextField(max_length=1200, null=True)),
                ('workhome', models.BooleanField(default=False, verbose_name='Work from home')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of publishing')),
                ('experience', models.CharField(blank=True, choices=[('NOEXP', 'Без опыта'), ('INTERN', 'После стажировки'), ('1TO3', 'От 1 до 3 лет'), ('3TO6', 'От 3 до 6 лет'), ('SIX', 'Более 6 лет')], max_length=20)),
                ('jobtype', models.CharField(blank=True, choices=[('FULL', 'Full-time'), ('PART', 'Part-time'), ('TRAINEE', 'Стажировка'), ('TEMPORARY', 'Временно')], max_length=20)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies.category')),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='users.employermore')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
