# Generated by Django 4.1.7 on 2023-05-26 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Name of vacancie')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='The city of job')),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('discription', models.TextField(max_length=600, null=True)),
                ('workhome', models.BooleanField(default=False, verbose_name='Work from home or not')),
                ('experience', models.CharField(blank=True, choices=[('NOEXP', 'Без опыта'), ('INTERN', 'После стажировки'), ('1TO3', 'От 1 года до 3 лет'), ('3TO6', 'От 3 лет до 6 лет'), ('SIX', 'Более 6 лет')], max_length=20)),
                ('jobtype', models.CharField(blank=True, choices=[('FULL', 'Full-time'), ('PART', 'Part-time'), ('TRAINEE', 'Стажировка'), ('TEMPORARY', 'Временно')], max_length=20)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies.category')),
            ],
        ),
    ]
