# Generated by Django 4.1.7 on 2023-05-26 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_vacancy_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ('-created_at',)},
        ),
    ]
