# Generated by Django 4.1.7 on 2023-05-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_alter_vacancy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='company_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Name of company'),
        ),
    ]
