# Generated by Django 4.1.7 on 2023-06-03 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_vacancy_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='discription',
            new_name='description',
        ),
    ]
