# Generated by Django 4.1.7 on 2023-06-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_rename_discription_vacancy_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='city',
            field=models.CharField(max_length=30, null=True, verbose_name='The city of job'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Name of company'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Name of vacancie'),
        ),
    ]
