# Generated by Django 4.1.7 on 2023-06-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_alter_vacancy_city_alter_vacancy_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(max_length=1200, null=True),
        ),
    ]
