# Generated by Django 5.0.4 on 2024-04-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_alter_vacancy_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(blank=True, choices=[('NOEXP', 'Без опыта'), ('INTERN', 'После стажировки'), ('1TO3', 'От 1 до 3 лет'), ('3TO6', 'От 3 до 6 лет'), ('SIX', 'Более 6 лет')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Name of vacancy'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='workhome',
            field=models.BooleanField(default=False, verbose_name='Work from home'),
        ),
    ]
