# Generated by Django 5.0.4 on 2024-05-16 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_employermore_testfield_employermore_about_and_more'),
        ('vacancies', '0008_alter_vacancy_experience_alter_vacancy_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='users.employermore'),
        ),
    ]
