# Generated by Django 5.0.4 on 2024-05-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employermore',
            name='testfield',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
