# Generated by Django 5.0.4 on 2024-05-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_employermore_testfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='workermore',
            name='testfield',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
