# Generated by Django 5.0.4 on 2024-06-07 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployerStorage',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
