# Generated by Django 5.0.4 on 2024-06-12 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultstorage',
            name='amount',
        ),
    ]
