# Generated by Django 5.0.4 on 2024-06-12 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_remove_defaultstorage_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyeStorage',
            fields=[
                ('defaultstorage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='storage.defaultstorage')),
            ],
            bases=('storage.defaultstorage',),
        ),
    ]
