# Generated by Django 5.0.4 on 2024-06-25 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_replyestorage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='defaultstorage',
            unique_together=set(),
        ),
    ]
