# Generated by Django 5.0.4 on 2024-07-05 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_alter_defaultstorage_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replyestorage',
            name='defaultstorage_ptr',
        ),
        migrations.DeleteModel(
            name='DefaultStorage',
        ),
        migrations.DeleteModel(
            name='ReplyeStorage',
        ),
    ]
